# Generated by Django 2.2.5 on 2020-02-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(default=''),
        ),
    ]
