# Generated by Django 2.2.5 on 2020-02-28 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200228_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='instant_block',
            new_name='instant_book',
        ),
    ]
