# Generated by Django 2.2.5 on 2020-03-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20200319_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='room',
            name='baths',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='instant_book',
            field=models.BooleanField(default=False),
        ),
    ]
